version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: whatsapp_db
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  whatsapp-api:
    build: .
    image: whatsapp-api:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/whatsapp_db
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: spring@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_ROOT_PICTURE_DIR: ./root/picture
      APP_ROOT_VIDEO_DIR: ./root/video
    ports:
      - "8000:8000"
    volumes:
      - ./root:/app/root
    restart: always

  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.6
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

volumes:
  pgdata:
